disabled_rules:
  - trailing_whitespace
excluded:
  - SpaceX-GraphQL/Data/GraphQL/API.swift
opt_in_rules:
  - force_unwrapping
cyclomatic_complexity:
  ignores_case_statements: true
force_cast: warning
force_try:
  severity: warning
line_length:
  warning: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
identifier_name:
  excluded:
    - x
    - y
    - id
    - url
    - on
